services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: springboot-app
    ports:
      - "5050:5050"   # server.port
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
