name: Close Jira issue
on:
  issues:
    types: [closed]

jobs:
  close-issue:
    name: Close Jira issue
    runs-on: ubuntu-latest

    steps:
      # 1) main 브랜치 체크아웃 → 템플릿이 있는 브랜치
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # 2) Jira 로그인
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL:   ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN:  ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      # 3) 이슈 제목이 [BUG]인지 아닌지를 보고 템플릿 선택
      - name: Select Issue-Form Template
        id: select-template
        run: |
          TITLE="${{ github.event.issue.title }}"
          if [[ "$TITLE" == "[BUG]"* ]]; then
            echo "template_path=.github/ISSUE_TEMPLATE/bug-report-form.yml" >> $GITHUB_OUTPUT
          else
            echo "template_path=.github/ISSUE_TEMPLATE/feature-request-form.yml" >> $GITHUB_OUTPUT
          fi

      # 4) Issue Parser (jiraKey만 추출하면 됨)
      - name: Issue Parser
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: ${{ steps.select-template.outputs.template_path }}
          issue-body:    ${{ github.event.issue.body }}

      # 5) 디버깅: jiraKey 출력
      - name: Log parsed Jira Key
        run: |
          echo "▶ jiraKey = '${{ steps.issue-parser.outputs.issueparser_jiraKey }}'"

      # 6) 자식 이슈를 완료 처리
      - name: Transition Jira issue to 완료
        if: ${{ steps.issue-parser.outputs.issueparser_jiraKey != '' }}
        uses: atlassian/gajira-transition@v3
        with:
          issue:        ${{ steps.issue-parser.outputs.issueparser_jiraKey }}
          transitionId: '31'   # “완료(Done)” 트랜지션 ID
