name: Close Jira issue
on:
  issues:
    types: [closed]

jobs:
  close-issue:
    name: Close linked Jira issue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL:   ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN:  ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      # 조건 분기로 템플릿 분리 - run 제거
      - name: Use BUG template
        if: startsWith(github.event.issue.title, '[BUG]')
        id: select-bug
        run: echo "template_path=.github/ISSUE_TEMPLATE/bug-report-form.yml" >> $GITHUB_OUTPUT

      - name: Use FEATURE template
        if: ${{ !startsWith(github.event.issue.title, '[BUG]') }}
        id: select-feature
        run: echo "template_path=.github/ISSUE_TEMPLATE/feature-request-form.yml" >> $GITHUB_OUTPUT

      - name: Parse GitHub Issue
        uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: ${{ steps.select-bug.outputs.template_path || steps.select-feature.outputs.template_path }}
          issue-body:    ${{ github.event.issue.body }}

      - name: Transition Jira issue to 완료
        uses: atlassian/gajira-transition@v3
        with:
          issue:        ${{ steps.issue-parser.outputs.issueparser_jiraKey }}
          transitionId: '31'
